// Code generated by ent, DO NOT EDIT.

package runtime

import (
	"github.com/google/uuid"
	"github.com/intyouss/AI-Task-Hub/ent/schema"
	"github.com/intyouss/AI-Task-Hub/ent/task"
	"github.com/intyouss/AI-Task-Hub/ent/timemixin"
	"github.com/intyouss/AI-Task-Hub/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	taskMixin := schema.Task{}.Mixin()
	taskMixinHooks0 := taskMixin[0].Hooks()
	task.Hooks[0] = taskMixinHooks0[0]
	task.Hooks[1] = taskMixinHooks0[1]
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescID is the schema descriptor for id field.
	taskDescID := taskFields[0].Descriptor()
	// task.DefaultID holds the default value on creation for the id field.
	task.DefaultID = taskDescID.Default.(func() uuid.UUID)
	timemixinHooks := schema.TimeMixin{}.Hooks()
	timemixin.Hooks[0] = timemixinHooks[0]
	timemixin.Hooks[1] = timemixinHooks[1]
	userMixin := schema.User{}.Mixin()
	userMixinHooks0 := userMixin[0].Hooks()
	user.Hooks[0] = userMixinHooks0[0]
	user.Hooks[1] = userMixinHooks0[1]
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescPhone is the schema descriptor for phone field.
	userDescPhone := userFields[3].Descriptor()
	// user.DefaultPhone holds the default value on creation for the phone field.
	user.DefaultPhone = userDescPhone.Default.(string)
	// userDescEmail is the schema descriptor for email field.
	userDescEmail := userFields[4].Descriptor()
	// user.DefaultEmail holds the default value on creation for the email field.
	user.DefaultEmail = userDescEmail.Default.(string)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
}

const (
	Version = "v0.14.5"                                         // Version of ent codegen.
	Sum     = "h1:Rj2WOYJtCkWyFo6a+5wB3EfBRP0rnx1fMk6gGA0UUe4=" // Sum of ent codegen.
)
