// Code generated by ent, DO NOT EDIT.

package softdeletemixin

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/intyouss/AI-Task-Hub/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int) predicate.SoftDeleteMixin {
	return predicate.SoftDeleteMixin(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int) predicate.SoftDeleteMixin {
	return predicate.SoftDeleteMixin(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int) predicate.SoftDeleteMixin {
	return predicate.SoftDeleteMixin(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int) predicate.SoftDeleteMixin {
	return predicate.SoftDeleteMixin(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int) predicate.SoftDeleteMixin {
	return predicate.SoftDeleteMixin(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int) predicate.SoftDeleteMixin {
	return predicate.SoftDeleteMixin(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int) predicate.SoftDeleteMixin {
	return predicate.SoftDeleteMixin(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int) predicate.SoftDeleteMixin {
	return predicate.SoftDeleteMixin(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int) predicate.SoftDeleteMixin {
	return predicate.SoftDeleteMixin(sql.FieldLTE(FieldID, id))
}

// DeletedAt applies equality check predicate on the "deleted_at" field. It's identical to DeletedAtEQ.
func DeletedAt(v time.Time) predicate.SoftDeleteMixin {
	return predicate.SoftDeleteMixin(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtEQ applies the EQ predicate on the "deleted_at" field.
func DeletedAtEQ(v time.Time) predicate.SoftDeleteMixin {
	return predicate.SoftDeleteMixin(sql.FieldEQ(FieldDeletedAt, v))
}

// DeletedAtNEQ applies the NEQ predicate on the "deleted_at" field.
func DeletedAtNEQ(v time.Time) predicate.SoftDeleteMixin {
	return predicate.SoftDeleteMixin(sql.FieldNEQ(FieldDeletedAt, v))
}

// DeletedAtIn applies the In predicate on the "deleted_at" field.
func DeletedAtIn(vs ...time.Time) predicate.SoftDeleteMixin {
	return predicate.SoftDeleteMixin(sql.FieldIn(FieldDeletedAt, vs...))
}

// DeletedAtNotIn applies the NotIn predicate on the "deleted_at" field.
func DeletedAtNotIn(vs ...time.Time) predicate.SoftDeleteMixin {
	return predicate.SoftDeleteMixin(sql.FieldNotIn(FieldDeletedAt, vs...))
}

// DeletedAtGT applies the GT predicate on the "deleted_at" field.
func DeletedAtGT(v time.Time) predicate.SoftDeleteMixin {
	return predicate.SoftDeleteMixin(sql.FieldGT(FieldDeletedAt, v))
}

// DeletedAtGTE applies the GTE predicate on the "deleted_at" field.
func DeletedAtGTE(v time.Time) predicate.SoftDeleteMixin {
	return predicate.SoftDeleteMixin(sql.FieldGTE(FieldDeletedAt, v))
}

// DeletedAtLT applies the LT predicate on the "deleted_at" field.
func DeletedAtLT(v time.Time) predicate.SoftDeleteMixin {
	return predicate.SoftDeleteMixin(sql.FieldLT(FieldDeletedAt, v))
}

// DeletedAtLTE applies the LTE predicate on the "deleted_at" field.
func DeletedAtLTE(v time.Time) predicate.SoftDeleteMixin {
	return predicate.SoftDeleteMixin(sql.FieldLTE(FieldDeletedAt, v))
}

// DeletedAtIsNil applies the IsNil predicate on the "deleted_at" field.
func DeletedAtIsNil() predicate.SoftDeleteMixin {
	return predicate.SoftDeleteMixin(sql.FieldIsNull(FieldDeletedAt))
}

// DeletedAtNotNil applies the NotNil predicate on the "deleted_at" field.
func DeletedAtNotNil() predicate.SoftDeleteMixin {
	return predicate.SoftDeleteMixin(sql.FieldNotNull(FieldDeletedAt))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SoftDeleteMixin) predicate.SoftDeleteMixin {
	return predicate.SoftDeleteMixin(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SoftDeleteMixin) predicate.SoftDeleteMixin {
	return predicate.SoftDeleteMixin(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SoftDeleteMixin) predicate.SoftDeleteMixin {
	return predicate.SoftDeleteMixin(sql.NotPredicates(p))
}
