// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// TasksColumns holds the columns for the "tasks" table.
	TasksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// TasksTable holds the schema information for the "tasks" table.
	TasksTable = &schema.Table{
		Name:       "tasks",
		Columns:    TasksColumns,
		PrimaryKey: []*schema.Column{TasksColumns[0]},
	}
	// TimeMixinsColumns holds the columns for the "time_mixins" table.
	TimeMixinsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
	}
	// TimeMixinsTable holds the schema information for the "time_mixins" table.
	TimeMixinsTable = &schema.Table{
		Name:       "time_mixins",
		Columns:    TimeMixinsColumns,
		PrimaryKey: []*schema.Column{TimeMixinsColumns[0]},
	}
	// UsersColumns holds the columns for the "users" table.
	UsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "nickname", Type: field.TypeString},
		{Name: "api_key", Type: field.TypeString},
		{Name: "phone", Type: field.TypeString, Default: ""},
		{Name: "email", Type: field.TypeString, Default: ""},
	}
	// UsersTable holds the schema information for the "users" table.
	UsersTable = &schema.Table{
		Name:       "users",
		Columns:    UsersColumns,
		PrimaryKey: []*schema.Column{UsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		TasksTable,
		TimeMixinsTable,
		UsersTable,
	}
)

func init() {
}
