// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/intyouss/AI-Task-Hub/ent/predicate"
	"github.com/intyouss/AI-Task-Hub/ent/softdeletemixin"
)

// SoftDeleteMixinDelete is the builder for deleting a SoftDeleteMixin entity.
type SoftDeleteMixinDelete struct {
	config
	hooks    []Hook
	mutation *SoftDeleteMixinMutation
}

// Where appends a list predicates to the SoftDeleteMixinDelete builder.
func (_d *SoftDeleteMixinDelete) Where(ps ...predicate.SoftDeleteMixin) *SoftDeleteMixinDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *SoftDeleteMixinDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SoftDeleteMixinDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *SoftDeleteMixinDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(softdeletemixin.Table, sqlgraph.NewFieldSpec(softdeletemixin.FieldID, field.TypeInt))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// SoftDeleteMixinDeleteOne is the builder for deleting a single SoftDeleteMixin entity.
type SoftDeleteMixinDeleteOne struct {
	_d *SoftDeleteMixinDelete
}

// Where appends a list predicates to the SoftDeleteMixinDelete builder.
func (_d *SoftDeleteMixinDeleteOne) Where(ps ...predicate.SoftDeleteMixin) *SoftDeleteMixinDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *SoftDeleteMixinDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{softdeletemixin.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *SoftDeleteMixinDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
