// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/intyouss/AI-Task-Hub/ent/softdeletemixin"
)

// SoftDeleteMixin is the model entity for the SoftDeleteMixin schema.
type SoftDeleteMixin struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// 删除时间
	DeletedAt    *time.Time `json:"deleted_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SoftDeleteMixin) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case softdeletemixin.FieldID:
			values[i] = new(sql.NullInt64)
		case softdeletemixin.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SoftDeleteMixin fields.
func (_m *SoftDeleteMixin) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case softdeletemixin.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int(value.Int64)
		case softdeletemixin.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SoftDeleteMixin.
// This includes values selected through modifiers, order, etc.
func (_m *SoftDeleteMixin) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this SoftDeleteMixin.
// Note that you need to call SoftDeleteMixin.Unwrap() before calling this method if this SoftDeleteMixin
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SoftDeleteMixin) Update() *SoftDeleteMixinUpdateOne {
	return NewSoftDeleteMixinClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SoftDeleteMixin entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SoftDeleteMixin) Unwrap() *SoftDeleteMixin {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SoftDeleteMixin is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SoftDeleteMixin) String() string {
	var builder strings.Builder
	builder.WriteString("SoftDeleteMixin(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// SoftDeleteMixins is a parsable slice of SoftDeleteMixin.
type SoftDeleteMixins []*SoftDeleteMixin
