// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/intyouss/AI-Task-Hub/ent/softdeletemixin"
)

// SoftDeleteMixinCreate is the builder for creating a SoftDeleteMixin entity.
type SoftDeleteMixinCreate struct {
	config
	mutation *SoftDeleteMixinMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetDeletedAt sets the "deleted_at" field.
func (_c *SoftDeleteMixinCreate) SetDeletedAt(v time.Time) *SoftDeleteMixinCreate {
	_c.mutation.SetDeletedAt(v)
	return _c
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_c *SoftDeleteMixinCreate) SetNillableDeletedAt(v *time.Time) *SoftDeleteMixinCreate {
	if v != nil {
		_c.SetDeletedAt(*v)
	}
	return _c
}

// Mutation returns the SoftDeleteMixinMutation object of the builder.
func (_c *SoftDeleteMixinCreate) Mutation() *SoftDeleteMixinMutation {
	return _c.mutation
}

// Save creates the SoftDeleteMixin in the database.
func (_c *SoftDeleteMixinCreate) Save(ctx context.Context) (*SoftDeleteMixin, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SoftDeleteMixinCreate) SaveX(ctx context.Context) *SoftDeleteMixin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SoftDeleteMixinCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SoftDeleteMixinCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SoftDeleteMixinCreate) check() error {
	return nil
}

func (_c *SoftDeleteMixinCreate) sqlSave(ctx context.Context) (*SoftDeleteMixin, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SoftDeleteMixinCreate) createSpec() (*SoftDeleteMixin, *sqlgraph.CreateSpec) {
	var (
		_node = &SoftDeleteMixin{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(softdeletemixin.Table, sqlgraph.NewFieldSpec(softdeletemixin.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.DeletedAt(); ok {
		_spec.SetField(softdeletemixin.FieldDeletedAt, field.TypeTime, value)
		_node.DeletedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SoftDeleteMixin.Create().
//		SetDeletedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SoftDeleteMixinUpsert) {
//			SetDeletedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SoftDeleteMixinCreate) OnConflict(opts ...sql.ConflictOption) *SoftDeleteMixinUpsertOne {
	_c.conflict = opts
	return &SoftDeleteMixinUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SoftDeleteMixin.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SoftDeleteMixinCreate) OnConflictColumns(columns ...string) *SoftDeleteMixinUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SoftDeleteMixinUpsertOne{
		create: _c,
	}
}

type (
	// SoftDeleteMixinUpsertOne is the builder for "upsert"-ing
	//  one SoftDeleteMixin node.
	SoftDeleteMixinUpsertOne struct {
		create *SoftDeleteMixinCreate
	}

	// SoftDeleteMixinUpsert is the "OnConflict" setter.
	SoftDeleteMixinUpsert struct {
		*sql.UpdateSet
	}
)

// SetDeletedAt sets the "deleted_at" field.
func (u *SoftDeleteMixinUpsert) SetDeletedAt(v time.Time) *SoftDeleteMixinUpsert {
	u.Set(softdeletemixin.FieldDeletedAt, v)
	return u
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SoftDeleteMixinUpsert) UpdateDeletedAt() *SoftDeleteMixinUpsert {
	u.SetExcluded(softdeletemixin.FieldDeletedAt)
	return u
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SoftDeleteMixinUpsert) ClearDeletedAt() *SoftDeleteMixinUpsert {
	u.SetNull(softdeletemixin.FieldDeletedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SoftDeleteMixin.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SoftDeleteMixinUpsertOne) UpdateNewValues() *SoftDeleteMixinUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SoftDeleteMixin.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SoftDeleteMixinUpsertOne) Ignore() *SoftDeleteMixinUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SoftDeleteMixinUpsertOne) DoNothing() *SoftDeleteMixinUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SoftDeleteMixinCreate.OnConflict
// documentation for more info.
func (u *SoftDeleteMixinUpsertOne) Update(set func(*SoftDeleteMixinUpsert)) *SoftDeleteMixinUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SoftDeleteMixinUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SoftDeleteMixinUpsertOne) SetDeletedAt(v time.Time) *SoftDeleteMixinUpsertOne {
	return u.Update(func(s *SoftDeleteMixinUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SoftDeleteMixinUpsertOne) UpdateDeletedAt() *SoftDeleteMixinUpsertOne {
	return u.Update(func(s *SoftDeleteMixinUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SoftDeleteMixinUpsertOne) ClearDeletedAt() *SoftDeleteMixinUpsertOne {
	return u.Update(func(s *SoftDeleteMixinUpsert) {
		s.ClearDeletedAt()
	})
}

// Exec executes the query.
func (u *SoftDeleteMixinUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SoftDeleteMixinCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SoftDeleteMixinUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SoftDeleteMixinUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SoftDeleteMixinUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SoftDeleteMixinCreateBulk is the builder for creating many SoftDeleteMixin entities in bulk.
type SoftDeleteMixinCreateBulk struct {
	config
	err      error
	builders []*SoftDeleteMixinCreate
	conflict []sql.ConflictOption
}

// Save creates the SoftDeleteMixin entities in the database.
func (_c *SoftDeleteMixinCreateBulk) Save(ctx context.Context) ([]*SoftDeleteMixin, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SoftDeleteMixin, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SoftDeleteMixinMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SoftDeleteMixinCreateBulk) SaveX(ctx context.Context) []*SoftDeleteMixin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SoftDeleteMixinCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SoftDeleteMixinCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SoftDeleteMixin.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SoftDeleteMixinUpsert) {
//			SetDeletedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *SoftDeleteMixinCreateBulk) OnConflict(opts ...sql.ConflictOption) *SoftDeleteMixinUpsertBulk {
	_c.conflict = opts
	return &SoftDeleteMixinUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SoftDeleteMixin.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SoftDeleteMixinCreateBulk) OnConflictColumns(columns ...string) *SoftDeleteMixinUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SoftDeleteMixinUpsertBulk{
		create: _c,
	}
}

// SoftDeleteMixinUpsertBulk is the builder for "upsert"-ing
// a bulk of SoftDeleteMixin nodes.
type SoftDeleteMixinUpsertBulk struct {
	create *SoftDeleteMixinCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SoftDeleteMixin.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SoftDeleteMixinUpsertBulk) UpdateNewValues() *SoftDeleteMixinUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SoftDeleteMixin.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SoftDeleteMixinUpsertBulk) Ignore() *SoftDeleteMixinUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SoftDeleteMixinUpsertBulk) DoNothing() *SoftDeleteMixinUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SoftDeleteMixinCreateBulk.OnConflict
// documentation for more info.
func (u *SoftDeleteMixinUpsertBulk) Update(set func(*SoftDeleteMixinUpsert)) *SoftDeleteMixinUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SoftDeleteMixinUpsert{UpdateSet: update})
	}))
	return u
}

// SetDeletedAt sets the "deleted_at" field.
func (u *SoftDeleteMixinUpsertBulk) SetDeletedAt(v time.Time) *SoftDeleteMixinUpsertBulk {
	return u.Update(func(s *SoftDeleteMixinUpsert) {
		s.SetDeletedAt(v)
	})
}

// UpdateDeletedAt sets the "deleted_at" field to the value that was provided on create.
func (u *SoftDeleteMixinUpsertBulk) UpdateDeletedAt() *SoftDeleteMixinUpsertBulk {
	return u.Update(func(s *SoftDeleteMixinUpsert) {
		s.UpdateDeletedAt()
	})
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (u *SoftDeleteMixinUpsertBulk) ClearDeletedAt() *SoftDeleteMixinUpsertBulk {
	return u.Update(func(s *SoftDeleteMixinUpsert) {
		s.ClearDeletedAt()
	})
}

// Exec executes the query.
func (u *SoftDeleteMixinUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SoftDeleteMixinCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SoftDeleteMixinCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SoftDeleteMixinUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
