// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/intyouss/AI-Task-Hub/ent/timemixin"
)

// TimeMixinCreate is the builder for creating a TimeMixin entity.
type TimeMixinCreate struct {
	config
	mutation *TimeMixinMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *TimeMixinCreate) SetCreatedAt(v time.Time) *TimeMixinCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *TimeMixinCreate) SetNillableCreatedAt(v *time.Time) *TimeMixinCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *TimeMixinCreate) SetUpdatedAt(v time.Time) *TimeMixinCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *TimeMixinCreate) SetNillableUpdatedAt(v *time.Time) *TimeMixinCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// Mutation returns the TimeMixinMutation object of the builder.
func (_c *TimeMixinCreate) Mutation() *TimeMixinMutation {
	return _c.mutation
}

// Save creates the TimeMixin in the database.
func (_c *TimeMixinCreate) Save(ctx context.Context) (*TimeMixin, error) {
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *TimeMixinCreate) SaveX(ctx context.Context) *TimeMixin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TimeMixinCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TimeMixinCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *TimeMixinCreate) check() error {
	return nil
}

func (_c *TimeMixinCreate) sqlSave(ctx context.Context) (*TimeMixin, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *TimeMixinCreate) createSpec() (*TimeMixin, *sqlgraph.CreateSpec) {
	var (
		_node = &TimeMixin{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(timemixin.Table, sqlgraph.NewFieldSpec(timemixin.FieldID, field.TypeInt))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(timemixin.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = &value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(timemixin.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = &value
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TimeMixin.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TimeMixinUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TimeMixinCreate) OnConflict(opts ...sql.ConflictOption) *TimeMixinUpsertOne {
	_c.conflict = opts
	return &TimeMixinUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TimeMixin.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TimeMixinCreate) OnConflictColumns(columns ...string) *TimeMixinUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TimeMixinUpsertOne{
		create: _c,
	}
}

type (
	// TimeMixinUpsertOne is the builder for "upsert"-ing
	//  one TimeMixin node.
	TimeMixinUpsertOne struct {
		create *TimeMixinCreate
	}

	// TimeMixinUpsert is the "OnConflict" setter.
	TimeMixinUpsert struct {
		*sql.UpdateSet
	}
)

// SetCreatedAt sets the "created_at" field.
func (u *TimeMixinUpsert) SetCreatedAt(v time.Time) *TimeMixinUpsert {
	u.Set(timemixin.FieldCreatedAt, v)
	return u
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *TimeMixinUpsert) UpdateCreatedAt() *TimeMixinUpsert {
	u.SetExcluded(timemixin.FieldCreatedAt)
	return u
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *TimeMixinUpsert) ClearCreatedAt() *TimeMixinUpsert {
	u.SetNull(timemixin.FieldCreatedAt)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TimeMixinUpsert) SetUpdatedAt(v time.Time) *TimeMixinUpsert {
	u.Set(timemixin.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TimeMixinUpsert) UpdateUpdatedAt() *TimeMixinUpsert {
	u.SetExcluded(timemixin.FieldUpdatedAt)
	return u
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *TimeMixinUpsert) ClearUpdatedAt() *TimeMixinUpsert {
	u.SetNull(timemixin.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.TimeMixin.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TimeMixinUpsertOne) UpdateNewValues() *TimeMixinUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TimeMixin.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *TimeMixinUpsertOne) Ignore() *TimeMixinUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TimeMixinUpsertOne) DoNothing() *TimeMixinUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TimeMixinCreate.OnConflict
// documentation for more info.
func (u *TimeMixinUpsertOne) Update(set func(*TimeMixinUpsert)) *TimeMixinUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TimeMixinUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *TimeMixinUpsertOne) SetCreatedAt(v time.Time) *TimeMixinUpsertOne {
	return u.Update(func(s *TimeMixinUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *TimeMixinUpsertOne) UpdateCreatedAt() *TimeMixinUpsertOne {
	return u.Update(func(s *TimeMixinUpsert) {
		s.UpdateCreatedAt()
	})
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *TimeMixinUpsertOne) ClearCreatedAt() *TimeMixinUpsertOne {
	return u.Update(func(s *TimeMixinUpsert) {
		s.ClearCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TimeMixinUpsertOne) SetUpdatedAt(v time.Time) *TimeMixinUpsertOne {
	return u.Update(func(s *TimeMixinUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TimeMixinUpsertOne) UpdateUpdatedAt() *TimeMixinUpsertOne {
	return u.Update(func(s *TimeMixinUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *TimeMixinUpsertOne) ClearUpdatedAt() *TimeMixinUpsertOne {
	return u.Update(func(s *TimeMixinUpsert) {
		s.ClearUpdatedAt()
	})
}

// Exec executes the query.
func (u *TimeMixinUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TimeMixinCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TimeMixinUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *TimeMixinUpsertOne) ID(ctx context.Context) (id int, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *TimeMixinUpsertOne) IDX(ctx context.Context) int {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// TimeMixinCreateBulk is the builder for creating many TimeMixin entities in bulk.
type TimeMixinCreateBulk struct {
	config
	err      error
	builders []*TimeMixinCreate
	conflict []sql.ConflictOption
}

// Save creates the TimeMixin entities in the database.
func (_c *TimeMixinCreateBulk) Save(ctx context.Context) ([]*TimeMixin, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*TimeMixin, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*TimeMixinMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *TimeMixinCreateBulk) SaveX(ctx context.Context) []*TimeMixin {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *TimeMixinCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *TimeMixinCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.TimeMixin.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.TimeMixinUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *TimeMixinCreateBulk) OnConflict(opts ...sql.ConflictOption) *TimeMixinUpsertBulk {
	_c.conflict = opts
	return &TimeMixinUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.TimeMixin.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *TimeMixinCreateBulk) OnConflictColumns(columns ...string) *TimeMixinUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &TimeMixinUpsertBulk{
		create: _c,
	}
}

// TimeMixinUpsertBulk is the builder for "upsert"-ing
// a bulk of TimeMixin nodes.
type TimeMixinUpsertBulk struct {
	create *TimeMixinCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.TimeMixin.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *TimeMixinUpsertBulk) UpdateNewValues() *TimeMixinUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.TimeMixin.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *TimeMixinUpsertBulk) Ignore() *TimeMixinUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *TimeMixinUpsertBulk) DoNothing() *TimeMixinUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the TimeMixinCreateBulk.OnConflict
// documentation for more info.
func (u *TimeMixinUpsertBulk) Update(set func(*TimeMixinUpsert)) *TimeMixinUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&TimeMixinUpsert{UpdateSet: update})
	}))
	return u
}

// SetCreatedAt sets the "created_at" field.
func (u *TimeMixinUpsertBulk) SetCreatedAt(v time.Time) *TimeMixinUpsertBulk {
	return u.Update(func(s *TimeMixinUpsert) {
		s.SetCreatedAt(v)
	})
}

// UpdateCreatedAt sets the "created_at" field to the value that was provided on create.
func (u *TimeMixinUpsertBulk) UpdateCreatedAt() *TimeMixinUpsertBulk {
	return u.Update(func(s *TimeMixinUpsert) {
		s.UpdateCreatedAt()
	})
}

// ClearCreatedAt clears the value of the "created_at" field.
func (u *TimeMixinUpsertBulk) ClearCreatedAt() *TimeMixinUpsertBulk {
	return u.Update(func(s *TimeMixinUpsert) {
		s.ClearCreatedAt()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *TimeMixinUpsertBulk) SetUpdatedAt(v time.Time) *TimeMixinUpsertBulk {
	return u.Update(func(s *TimeMixinUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *TimeMixinUpsertBulk) UpdateUpdatedAt() *TimeMixinUpsertBulk {
	return u.Update(func(s *TimeMixinUpsert) {
		s.UpdateUpdatedAt()
	})
}

// ClearUpdatedAt clears the value of the "updated_at" field.
func (u *TimeMixinUpsertBulk) ClearUpdatedAt() *TimeMixinUpsertBulk {
	return u.Update(func(s *TimeMixinUpsert) {
		s.ClearUpdatedAt()
	})
}

// Exec executes the query.
func (u *TimeMixinUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the TimeMixinCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for TimeMixinCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *TimeMixinUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
