// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// SoftDeleteMixin is the predicate function for softdeletemixin builders.
type SoftDeleteMixin func(*sql.Selector)

// Task is the predicate function for task builders.
type Task func(*sql.Selector)

// TimeMixin is the predicate function for timemixin builders.
type TimeMixin func(*sql.Selector)

// User is the predicate function for user builders.
type User func(*sql.Selector)
